name: World_TPV2
version: 1.0.0
main: WorldTP\Main
api: [5.0.0]
author: brayanag2000

commands:
  wtp:
    description: Loads a world and teleports the player to it.
    usage: "/wtp <world_name>"
    permission: wtp.command
permissions:
  wtp.command:
    description: Used with /wtp
    default: true
license: CC BY-NC 4.0
